### PR TITLE
Bug: Add QACERT-11-A QCE screen check #1450

### LINKED ISSUE #5786: Bug: Add QACERT-11-A QCE screen check
Issue1:
QA Cert Event modal will let you save an event with a null Monitoring System ID and Component ID
Steps to Recreate:
Barry (3) 1, 2, CS0AAN
1. Select a configuration from the QA Cert Event Data & Test Extension Exemption Data screen
2. Add/ Edit a QA Cert Event
3. Make the Monitoring System ID and Component ID null
4. Save

Issue 2:
Barry (3) 1, 2, CS0AAN
QA Cert Event modal will let you save an event with a null QA Cert Event Code and Required Test Code
Steps to Recreate:
1. Select a configuration from the QA Cert Event Data & Test Extension Exemption Data screen
2. Add/ Edit a QA Cert Event
3. Make the QA Cert Event Code and Required Test Code null
4. Save

### PR DESCRIPTION
**Pull request by usmanahmederg**
Ticket
https://github.com/US-EPA-CAMD/easey-ui/issues/5786

Changes
Fixed the bug for saving null values for monitoring system id, component id and required test code.
Screenshot 2024-06-20 155728
Screenshot 2024-06-20 155919

### CODE REVIEW

**Comment by ergjustin** [comment]
I do not think these changes will modify **QACERT-11-A**

**Comment by usmanahmederg** [comment]
> I do not think these changes will modify **QACERT-11-A**

Can you please elaborate this comment. If you can point out the issue with the solution that would be much appreciated, because the solution is working fine and would love to hear your feedback if something is wrong. :)

**Comment by ergjustin** [comment]
The requirement for this ticket is to add a QACERT-11-A error message when creating a duplicate QA Cert event.([link](https://github.com/US-EPA-CAMD/easey-ui/issues/5786#issuecomment-2050273004))
I was able to generate the QACERT-11-A error code without making any code changes.

**Comment by ergjustin** [comment]
Please close this PR and delete the branch

**Pull request closed without merging**
