### PR TITLE
✨ Feature/2934-2935: API Endpoint - Add & View Cycle Time Summary Data

### PR DESCRIPTION
**Pull request by subrataroyCVP**
## [#2935](https://app.zenhub.com/workspaces/emissioners-scrum-board-5f36cd263511ad001a777f8e/issues/us-epa-camd/easey-ui/2935)

### CODE REVIEW

**Comment by subrataroyCVP** [comment]
image
image

image

**Review by RobertB-CVP — APPROVED** [review]

**Review by billmiller13 — APPROVED** [review]
Remove unused vars and module dependencies from src/cycle-time-summary/cycle-time-summary.controller.spec.ts

**Comment by subrataroyCVP** [comment]
> Remove unused vars and module dependencies from src/cycle-time-summary/cycle-time-summary.controller.spec.ts

Removed.

**Review by billmiller13 — APPROVED** [review]
lgtm

**Pull request merged**
